package Genertor.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static SNode sourceNodeQuery_5001228142444293938(final SourceSubstituteMacroNodeContext _context) {
    return SConceptOperations.createNewNode("com.mbeddr.core.statements.structure.ForStatement", null);
  }
}
