package FunctionContract.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ReturnValueRange_Constraints extends BaseConstraintsDescriptor {
  public ReturnValueRange_Constraints() {
    super(MetaIdFactory.conceptId(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa2dcc88L));
  }
}
