package FunctionContract.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class toggleVerifiable_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public toggleVerifiable_Intention() {
  }
  public String getConcept() {
    return "com.mbeddr.core.modules.structure.Function";
  }
  public String getPresentation() {
    return "toggleVerifiable";
  }
  public String getPersistentStateKey() {
    return "FunctionContract.intentions.toggleVerifiable_Intention";
  }
  public String getLanguageFqName() {
    return "FunctionContract";
  }
  public IntentionType getType() {
    return IntentionType.NORMAL;
  }
  public boolean isAvailableInChildNodes() {
    return false;
  }
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:7333a1b7-8a8d-4366-b9c4-2eba12a838c1(FunctionContract.intentions)", "8361579023105111573");
  }
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new toggleVerifiable_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }
  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "toggleVerifable";
    }
    public void execute(final SNode node, final EditorContext editorContext) {
      if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x740a4bd1e9846222L, "FunctionContract.structure.VerifyFunctionAttribute"))) == null)) {
        AttributeOperations.createAndSetAttrbiute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x740a4bd1e9846222L, "FunctionContract.structure.VerifyFunctionAttribute")), "FunctionContract.structure.VerifyFunctionAttribute");
      } else {
        SNodeOperations.deleteNode(AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x740a4bd1e9846222L, "FunctionContract.structure.VerifyFunctionAttribute"))));
      }
    }
    public IntentionDescriptor getDescriptor() {
      return toggleVerifiable_Intention.this;
    }
  }
}
