package FunctionContract.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class ArgReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ArgReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.ArgReference";
  }
}
