package FunctionContract.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class CheckFunctionPreconditions_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, MetaAdapterFactory.getProperty(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x20f3eab72c4e7a51L, 0x84c9f934cdfa961L, "assumed"), "" + (false));
  }
  public static void call_setAssumed_598028305536724302(SNode thisNode) {
    SPropertyOperations.set(thisNode, MetaAdapterFactory.getProperty(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x20f3eab72c4e7a51L, 0x84c9f934cdfa961L, "assumed"), "" + (true));
  }
  public static void call_setUnAssumed_598028305536729000(SNode thisNode) {
    SPropertyOperations.set(thisNode, MetaAdapterFactory.getProperty(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x20f3eab72c4e7a51L, 0x84c9f934cdfa961L, "assumed"), "" + (false));
  }
}
