package FunctionContract.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class CheckFunctionPreconditions_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public CheckFunctionPreconditions_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.CheckFunctionPreconditions";
  }
}
