package FunctionContract.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class CheckFunctionPostcondition_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public CheckFunctionPostcondition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.CheckFunctionPostcondition";
  }
}
