package FunctionContract.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IModuleContent_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.IExternable_BehaviorDescriptor;
import jetbrains.mps.lang.traceable.behavior.TraceableConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.core.base.behavior.IShowUpInOutline_Behavior;
import com.mbeddr.core.modules.behavior.IModuleContent_Behavior;
import org.jetbrains.mps.openapi.language.SConcept;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import javax.swing.Icon;
import com.mbeddr.mpsutil.breadcrumb.behavior.IBreadcrumb_Behavior;
import java.util.List;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.lang.traceable.behavior.TraceableConcept_Behavior;

public class FunctionContract_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IModuleContent_BehaviorDescriptor, IExternable_BehaviorDescriptor, TraceableConcept_BehaviorDescriptor {
  public FunctionContract_BehaviorDescriptor() {
  }
  public boolean virtual_actuallyShowInOutline_3789096399633594747(SNode thisNode) {
    return IShowUpInOutline_Behavior.virtual_actuallyShowInOutline_3789096399633594747(thisNode);
  }
  public Iterable<SNode> virtual_allReferencedModuleContents_1798411515023042202(SNode thisNode) {
    return IModuleContent_Behavior.virtual_allReferencedModuleContents_1798411515023042202(thisNode);
  }
  public boolean virtual_allowEverythingExceptWhitespace_151435140526267396(SConcept thisConcept) {
    return IIdentifierNamedConcept_Behavior.virtual_allowEverythingExceptWhitespace_151435140526267396(thisConcept);
  }
  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept thisConcept) {
    return IIdentifierNamedConcept_Behavior.virtual_allowNonIdentifierNames_6584628407655574550(thisConcept);
  }
  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }
  public SNode virtual_createImportedProxy_55677248263987031(SNode thisNode) {
    return IModuleContent_Behavior.virtual_createImportedProxy_55677248263987031(thisNode);
  }
  public boolean virtual_exportable_6584628407655574574(SConcept thisConcept) {
    return IModuleContent_Behavior.virtual_exportable_6584628407655574574(thisConcept);
  }
  public Icon virtual_getBreadcrumbIcon_5003834500845999512(SNode thisNode) {
    return IBreadcrumb_Behavior.virtual_getBreadcrumbIcon_5003834500845999512(thisNode);
  }
  public String virtual_getBreadcrumbText_4313262807135907204(SNode thisNode) {
    return IBreadcrumb_Behavior.virtual_getBreadcrumbText_4313262807135907204(thisNode);
  }
  public List<SAbstractConcept> virtual_getCommentConcept_6584628407655574603(SConcept thisConcept) {
    return IModuleContent_Behavior.virtual_getCommentConcept_6584628407655574603(thisConcept);
  }
  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }
  @Nullable
  public String virtual_getTraceableProperty_5067982036267369901(SNode thisNode) {
    return TraceableConcept_Behavior.virtual_getTraceableProperty_5067982036267369901(thisNode);
  }
  public boolean virtual_isCommentable_4457953124863306087(SNode thisNode, SNode trigger) {
    return IModuleContent_Behavior.virtual_isCommentable_4457953124863306087(thisNode, trigger);
  }
  public String virtual_kindString_6641971848870642999(SNode thisNode) {
    return IModuleContent_Behavior.virtual_kindString_6641971848870642999(thisNode);
  }
  public String virtual_mangledNameNew_7475861851228904359(SNode thisNode) {
    return IModuleContent_Behavior.virtual_mangledNameNew_7475861851228904359(thisNode);
  }
  public String virtual_mangledName_1317894735999377422(SNode thisNode) {
    return IModuleContent_Behavior.virtual_mangledName_1317894735999377422(thisNode);
  }
  public boolean virtual_needsReferenceQualifier_1317894735999315639(SNode thisNode, SNode sourceModule) {
    return IModuleContent_Behavior.virtual_needsReferenceQualifier_1317894735999315639(thisNode, sourceModule);
  }
  public boolean virtual_preventNameMangling_6708182213627106041(SNode thisNode) {
    return IModuleContent_Behavior.virtual_preventNameMangling_6708182213627106041(thisNode);
  }
  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }
  public String virtual_referenceQualifier_1317894735999315602(SNode thisNode) {
    return IModuleContent_Behavior.virtual_referenceQualifier_1317894735999315602(thisNode);
  }
  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }
  public boolean virtual_showInBreadcrumb_1609581366351617259(SNode thisNode) {
    return IModuleContent_Behavior.virtual_showInBreadcrumb_1609581366351617259(thisNode);
  }
  public int virtual_sortWeight_7999989049973036118(SNode thisNode) {
    return IModuleContent_Behavior.virtual_sortWeight_7999989049973036118(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.FunctionContract";
  }
}
