package FunctionContract.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class FunctionContract_Behavior {
  public static void init(SNode thisNode) {
    FunctionContract_Behavior.call_makeVars_3598327450488743691(thisNode);
  }
  public static void call_addArgs_2742180936282602292(SNode thisNode) {
    if ((SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa2bf3a8L, "function")) == null)) {
      return;
    }
    for (SNode arg : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa2bf3a8L, "function")), MetaAdapterFactory.getReferenceLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x76ad8d576f018e43L, 0x76ad8d576f018e45L, "function")), MetaAdapterFactory.getContainmentLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x707ac195dd5d51f2L, 0x4f39f90935e92f45L, "arguments")))) {
      SNode prec = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd7637eL, "FunctionContract.structure.ParameterRange")));
      SNode argref = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x7633a1580da963bcL, "FunctionContract.structure.ArgReference")));
      SLinkOperations.setTarget(argref, MetaAdapterFactory.getReferenceLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x7633a1580da963bcL, 0x7633a1580da980b5L, "Arg"), arg);
      SLinkOperations.setTarget(prec, MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd7637eL, 0x31efd3c05fdf0581L, "ConditionExp"), SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x260e2f0869006e10L, "FunctionContract.structure.RangeExpression"))));
      ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa247cebL, "preconditions")), MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd659d9L, 0x698df8585bd76378L, "ParameterRange"))).addElement(prec);
    }
  }
  public static void call_makeVars_3598327450488743691(SNode thisNode) {
    if (SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa2bf3a8L, "function")) == null) {
      return;
    }
    for (SNode arg : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa2bf3a8L, "function")), MetaAdapterFactory.getReferenceLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x76ad8d576f018e43L, 0x76ad8d576f018e45L, "function")), MetaAdapterFactory.getContainmentLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x707ac195dd5d51f2L, 0x4f39f90935e92f45L, "arguments")))) {
      SNode gvd = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x5bbe8a6d23a1b6ceL, "com.mbeddr.core.modules.structure.GlobalVariableDeclaration")));
      SLinkOperations.setTarget(gvd, MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x46a2a92ac61b183L, 0x46a2a92ac61b184L, "type"), SLinkOperations.getTarget(arg, MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x46a2a92ac61b183L, 0x46a2a92ac61b184L, "type")));
      SPropertyOperations.set(gvd, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), SPropertyOperations.getString(arg, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      ListSequence.fromList(SLinkOperations.getChildren(((SNode) SNodeOperations.getParent(thisNode)), MetaAdapterFactory.getContainmentLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x595522006a5b933dL, 0x595522006a5b9351L, "contents"))).addElement(gvd);
    }

  }
}
