package FunctionContract.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Postconditions_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Postconditions_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.Postconditions";
  }
}
