package FunctionContract.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Preconditions_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Preconditions_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.Preconditions";
  }
}
