package FunctionContract.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Preconditions_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, MetaAdapterFactory.getProperty(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd659d9L, 0x84c9f934d299e99L, "assumed"), "" + (false));
  }
}
