package FunctionContract.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RangeExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public RangeExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.RangeExpression";
  }
}
