package FunctionContract.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class ReturnValRef_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ReturnValRef_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.ReturnValRef";
  }
}
