package FunctionContract.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SideEffects_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SideEffects_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.SideEffects";
  }
}
