package FunctionContract.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class VerifyFunctionAttribute_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public VerifyFunctionAttribute_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "FunctionContract.structure.VerifyFunctionAttribute";
  }
}
