package PluginTest.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import com.mbeddr.core.base.pluginSolution.plugin.mbeddrPlatformEditorPopupGroup_ActionGroup;

public class PluginTest_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("PluginTest");
  public PluginTest_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new VerifyFunctions_Action());
    // groups 
    addGroup(new VerifyFS_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(VerifyFS_ActionGroup.ID, mbeddrPlatformEditorPopupGroup_ActionGroup.ID, mbeddrPlatformEditorPopupGroup_ActionGroup.LABEL_ID_mbeddrPlatformEditorPopupAnalysisExtensions);
  }
}
