package PluginTest.plugin;

/*Generated by MPS */

import com.mbeddr.analyses.cbmc.core.rt.analyses.asserts.CBMCAssertResult;
import java.util.List;
import com.mbeddr.analyses.cbmc.rt.counterexample.lifted.model.CBMCLiftedCounterexampleState;
import com.mbeddr.analyses.cbmc.rt.counterexample.raw.CBMCRawResult;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.analyses.cbmc.rt.counterexample.lifted.model.CBMCLiftedResult;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class VerifyFunctionResult extends CBMCAssertResult {
  private boolean noAssertionsFound = false;

  private List<CBMCLiftedCounterexampleState> lstates;
  public VerifyFunctionResult(CBMCRawResult raws, List<CBMCLiftedCounterexampleState> liftedstates, SNode analyzednode) {
    super(new CBMCLiftedResult(raws, raws.getDelayInMillis(), raws.getRawResultKind(), liftedstates, analyzednode));
    this.lstates = liftedstates;
  }

  public VerifyFunctionResult(CBMCLiftedResult liftedRes, String cbmclevelUserFriendlyMessage) {
    super(liftedRes, cbmclevelUserFriendlyMessage);
    noAssertionsFound = true;
  }


  public String getUserFriendlyMessage() {
    if (noAssertionsFound) {
      return "No Generated Assertion Found";
    }
    String msg = "";

    {
      boolean branchTaken_4723851297113497207 = false;
      if (!(branchTaken_4723851297113497207) && SNodeOperations.isInstanceOf(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x42270bafe92c4c32L, 0xb263d617b3fce239L, 0x60c769c35ee0b759L, "com.mbeddr.analyses.cbmc.structure.Assert"))) {
        branchTaken_4723851297113497207 = true;
        msg = BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget((SNodeOperations.cast(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x42270bafe92c4c32L, 0xb263d617b3fce239L, 0x60c769c35ee0b759L, "com.mbeddr.analyses.cbmc.structure.Assert"))), MetaAdapterFactory.getContainmentLink(0x42270bafe92c4c32L, 0xb263d617b3fce239L, 0x60c769c35ee0b759L, 0x60c769c35ee0b75aL, "exp")), "virtual_renderReadable_2231107713271337202", new Object[]{});
      }
      if (!(branchTaken_4723851297113497207) && SNodeOperations.isInstanceOf(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x42270bafe92c4c32L, 0xb263d617b3fce239L, 0x691a47ec49ad4116L, "com.mbeddr.analyses.cbmc.structure.VerificationConditionBase"))) {
        branchTaken_4723851297113497207 = true;
        msg = BehaviorReflection.invokeVirtual(String.class, (SNodeOperations.cast(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x42270bafe92c4c32L, 0xb263d617b3fce239L, 0x691a47ec49ad4116L, "com.mbeddr.analyses.cbmc.structure.VerificationConditionBase"))), "virtual_renderReadable_4723851297113544991", new Object[]{});
      }
      if (!(branchTaken_4723851297113497207) && SNodeOperations.isInstanceOf(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd7637eL, "FunctionContract.structure.ParameterRange"))) {
        branchTaken_4723851297113497207 = true;
        msg = "@" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor((SNodeOperations.cast(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd7637eL, "FunctionContract.structure.ParameterRange"))), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, "FunctionContract.structure.FunctionContract"), false, false), MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa2bf3a8L, "function")), MetaAdapterFactory.getReferenceLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x76ad8d576f018e43L, 0x76ad8d576f018e45L, "function")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + ", Parameter: " + SPropertyOperations.getString(SLinkOperations.getTarget((SNodeOperations.cast(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd7637eL, "FunctionContract.structure.ParameterRange"))), MetaAdapterFactory.getReferenceLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x698df8585bd7637eL, 0x79083afa79eb5f5fL, "Arg")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
      if (!(branchTaken_4723851297113497207) && SNodeOperations.isInstanceOf(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa2dcc88L, "FunctionContract.structure.ReturnValueRange"))) {
        branchTaken_4723851297113497207 = true;
        msg = "@" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor((SNodeOperations.cast(this.getAnalyzedConcept(), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa2dcc88L, "FunctionContract.structure.ReturnValueRange"))), MetaAdapterFactory.getConcept(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, "FunctionContract.structure.FunctionContract"), false, false), MetaAdapterFactory.getContainmentLink(0x902ada2bdddc4d40L, 0x9436e13ab6ba878dL, 0x5d0fbbc0aa247ceaL, 0x5d0fbbc0aa2bf3a8L, "function")), MetaAdapterFactory.getReferenceLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x76ad8d576f018e43L, 0x76ad8d576f018e45L, "function")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + ", Return Value";
      }
      if (!(branchTaken_4723851297113497207)) {
        msg = "ASSERTION";
        branchTaken_4723851297113497207 = true;
      }
    }
    return msg;
  }


}
