package PluginTest.plugin;

/*Generated by MPS */

import com.mbeddr.analyses.cbmc.rt.run.CProverAnalyzerFactory;
import com.mbeddr.analyses.utils.analyzer.AnalyzerBase;
import com.intellij.openapi.progress.ProgressIndicator;

public class VerifyingFunctionAnalyzerFactory extends CProverAnalyzerFactory {

  public AnalyzerBase createAnalyzer(ProgressIndicator pi) {
    return new VerifyFunctionAnalyser(config, toolAdapter, pi);
  }
}
